image: ruby:2.5

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install --path vendor

# add a job called 'test'
test:
  stage: test
  script:
    - gem install jekyll
    - bundle exec jekyll build -d test/
  artifacts:
    paths:
    - test # generating site folder to be browsed or download
  except:
    - master # the 'test' job will affect all branches expect 'master'

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get install -y locales
    - echo "en_US UTF-8" > /etc/locale.gen
    - locale-gen en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - export LC_ALL=en_US.UTF-8
    - bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master # this job will affect only the 'master' branch
